

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: sa
    password: YWJhYmFnYWxhbWFnYQ==
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
